###
GET http://localhost:3000/

###
###
GET http://localhost:3000/post?sender=123

###
###
POST http://localhost:3000/post
Content-Type: application/json

{
    "message": "this is my new message2", 
    "sender" : "123"
}
###