###
GET http://localhost:3000/

###
###
GET http://localhost:3000/post/123

###
###
POST http://localhost:3000/post
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2E4NTYyY2E4OGQ2MzNkMmNlMjY1MzMiLCJpYXQiOjE2NzE5NzY3MzQsImV4cCI6MTY3MTk4MDMzNH0.qDEfW3sRN-UcLtHaSviWMmsL6h14unKnC-8ruYLL3wU
Content-Type: application/json

{
    "message": "this is my new message222", 
    "sender" : "123"
}
###
###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "uaas1qr@usr.usr", 
    "password": "12345"
}
###

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "uaas1qr@usr.usr", 
    "password": "12345"
}
###